
name: BlockShuffle
main: com.akshit.blockshuffle.BlockShufflePlugin
version: 1.0
api-version: 1.21
commands:
  startshuffle:
    description: Starts the block shuffle game
  myblock:
    description: Shows your current target block
